<a href="https://colab.research.google.com/github/dmortalla/ztm-complete-ai-ml-ds/blob/main/intro_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## 1. Data Types and Attributes

In [ ]:
# Numpy's main datatype is ndarray, a list of numbers
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [ ]:
# Check the datatype
type(a1)

numpy.ndarray

In [ ]:
# Create the array
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

# Display the array with its dimnesion, shape, amd size
print(f"The array is: {a2}")
print(f"Its dimension is {a2.ndim}, its shape is {a2.shape}, and its size is {a2.size}.")
print(f"The datatype is {a2.dtype} while the array is of type {type(a2)}.")


The array is: [[1.  2.  3.3]
 [4.  5.  6.5]]
Its dimension is 2, its shape is (2, 3), and its size is 6.
The datatype is float64 while the array is of type <class 'numpy.ndarray'>.


In [ ]:
# Create the array
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]
              ])
# Display the array with its dimnesion, shape, amd size
print(f"The array is: {a3}")
print(f"Its dimension is {a3.ndim}, its shape is {a3.shape}, and its size is {a3.size}.")
print(f"The datatype is {a3.dtype} while the array is of type {type(a3)}.")


The array is: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
Its dimension is 3, its shape is (2, 3, 3), and its size is 18.
The datatype is int32 while the array is of type <class 'numpy.ndarray'>.


In [ ]:
# Create the array
a4 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]
               ])
# Display the array with its dimnesion, shape, amd size
print(f"The array is: {a4}")
print(f"Its dimension is {a4.ndim}, its shape is {a4.shape}, and its size is {a4.size}.")
print(f"The datatype is {a4.dtype} while the array is of type {type(a4)}.")


The array is: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Its dimension is 3, its shape is (3, 2, 3), and its size is 18.
The datatype is int32 while the array is of type <class 'numpy.ndarray'>.


In [ ]:
# Create a 2-dim dataframe from a 2-dim Numpy array
import pandas as pd

df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [ ]:
# Create a 3-dim dataframe from a 3-dim Numpy array
# Step 1: Reshape the 3D array to 2D by flattening the last dim
a3_2d = a3.reshape(-1, a3.shape[-1])

# Step 1: Create the DataFrame using multi-inde to retain original 3D structure
index = pd.MultiIndex.from_product([range(s) for s in a3.shape[:-1]], names=['Dim1', 'Dim2'])
df_a3 = pd.DataFrame(a3_2d, index=index, columns=[f'Feature_{i}' for i in range(a3.shape[-1])])

print(df_a3)

           Feature_0  Feature_1  Feature_2
Dim1 Dim2                                 
0    0             1          2          3
     1             4          5          6
     2             7          8          9
1    0            10         11         12
     1            13         14         15
     2            16         17         18


In [ ]:
# Create a 3-dim dataframe from a 3-dim Numpy array
# Step 1: Reshape the 3D array to 2D by flattening the last dim
a4_2d = a4.reshape(-1, a4.shape[-1])

# Step 1: Create the DataFrame using multi-inde to retain original 3D structure
index = pd.MultiIndex.from_product([range(s) for s in a4.shape[:-1]], names=['Dim1', 'Dim2'])
df_a4 = pd.DataFrame(a4_2d, index=index, columns=[f'Feature_{i}' for i in range(a4.shape[-1])])

print(df_a4)

           Feature_0  Feature_1  Feature_2
Dim1 Dim2                                 
0    0             1          2          3
     1             4          5          6
1    0             7          8          9
     1            10         11         12
2    0            13         14         15
     1            16         17         18


## 2. Creating preset Numpy arrays
To view the docstring of a Numpy method, click [SHIFT + TAB] while inside the parentheses ( ).

In [ ]:
# Array of ones of given shape
ones = np.ones((2, 3), dtype='int32')
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
ones.dtype

dtype('int32')

In [ ]:
# Array of zeros
zeros = np.zeros((2, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
# Array of numbers in a range
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
# Array of random integers of given shape
random_array = np.random.randint(3, 10, size=(2, 4))
random_array

array([[6, 3, 8, 3],
       [7, 8, 5, 7]])

In [ ]:
# Array of random decimals between 0 and 1
random_arr2 = np.random.random((3, 5))
random_arr2

array([[0.4160358 , 0.16135503, 0.66660496, 0.76793943, 0.36958008],
       [0.89421287, 0.40943518, 0.61970636, 0.8547741 , 0.31083618],
       [0.79033786, 0.36148083, 0.49413014, 0.38522968, 0.81634273]])

In [ ]:
# Array of random decimals between 0 and 1 in a normal distribution
random_arr3 = np.random.rand(3, 5)
random_arr3

array([[0.312641  , 0.24925495, 0.88357152, 0.95112868, 0.97246333],
       [0.5656856 , 0.05055926, 0.32149055, 0.32148024, 0.10408621],
       [0.54442274, 0.04030426, 0.22185623, 0.97298944, 0.86427998]])